services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
    networks:
    - k2k-net
  
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - ENDPOINT_URL=${ENDPOINT_URL}
      - AGENT_URL=${AGENT_URL}
    depends_on:
      - ai-agent
      - endpoint
    networks:
    - k2k-net

  ai-agent:
    build: ./ai-agent
    ports:
      - "5000:5000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
    networks:
    - k2k-net

  endpoint:
    build: ./endpoint
    ports:
      - "8890:8890"  # Port du SPARQL endpoint Virtuoso
      - "1111:1111"  # Port pour isql (administration)
    networks:
    - k2k-net

networks:
  k2k-net:
    driver: bridge
